### ISSUE TITLE
Update Dockerfile for 3DS build

### ISSUE THREAD

**Issue by mkst** [sm64-port/sm64_3ds#12]
PR incoming...

**Comment by Gericom** [comment]
Wouldn't it be better to not use docker at all. It's totally not required. Idk if people prefer to use it.

**Comment by mkst** [comment]
There's no _requirement_ to use Docker to build any of the versions - N64/PC/3DS - it's just cleaner to run the build inside a docker container rather than polluting your local machine with a bunch of binaries/libraries.

**Comment by yllekz** [comment]
Docker should be the only way to do it tbh. Docker keeps it neat, containerized, and doesn't clutter up the system.
