### ISSUE TITLE
Credits Bugged

### ISSUE THREAD

**Issue by terrran0va** [sm64-port/sm64_3ds#20]
I made this account for a different reason, but I thought I would point this out while I am here.

I had the audacity to actually finish the whole game on my NN3DSXL. It ran super smooth, no complaints. But after I got to the end (aka 31 stars, BLJ'd the rest) and started the credits, the parts where the screens becomes a bit smaller and pans a bit to show the credits throws the entire game into almost 1/3rd of the screen, putting it in the bottom right corner, and making the credit text (and the gameplay itself) almost impossible to see. It's not super important, as I think gameplay is more important than the end credits in a port, but it would be a nice fix at some point.

I didn't compile it myself, I had help from a friend, so sorry if this is the wrong place for it, or if this is straight up the wrong decompiled me and my friend ended up compiling. 
Sorry and thanks for your help :)

Specifically, my homebrew launched calls it "sm64.us.f3dex2e.3dsx", just want to make that clear in case this is the wrong place and then someone can point me into the right direction.

Sorry for rambling, thanks for reading.

**Comment by BenoitCaron** [comment]
Isn't this issue a duplicate of [that one](https://github.com/sm64-port/sm64_3ds/issues/9)?

**Comment by terrran0va** [comment]
Geuss it is, I didnt see it, sorry.
