### ISSUE TITLE
[Request] 800px wide mode

### ISSUE THREAD

**Issue by RocketRobz** [sm64-port/sm64_3ds#3]
With the ability to use the HD models, they'd look better, if this was running 800px mode.
Even if those particular models aren't used, the picture quality would be improved.

**Comment by Gericom** [comment]
It is implemented now (bff447b0f3a27203702c06cdbaac5f6047f96dbf)

**Comment by j0w0** [comment]
is this mode always used? just built and i cant tell the difference :p (im not using hd models atm)

**Comment by Gericom** [comment]
It is enabled by default by a define in gfx_3ds.h. It only doesn't work on an old 2ds. Since those don't have a 800 pixel wide screen. (but on old 3ds models the port isn't always full speed anyway) The difference is subtile, but it is definitely sharper.
