### ISSUE TITLE
config.bin location

### ISSUE THREAD

**Issue by imasheep1** [sm64-port/sm64_3ds#8]
I've heard you can improve performance on the game by disabling sound
I've been told that, to do this, you should change the last 4 bytes of config.bin to 03 00 00 00
My problem is, I can't find SM64's config.bin anywhere
Where is it? And would it be possible to add some sort of options menu where you can change these in-game?

**Comment by vaguerant** [comment]
You appear to be confusing this port with the one by 3ds borb. There have been two ports of Mario 64 to the 3DS, and this one isn't the one you're talking about.

**Comment by imasheep1** [comment]
Ah, I see. Sorry for the confusion then. I had no idea there were two ports
